on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: CI
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=latest,name=iPad Pro (9.7-inch)']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Force Xcode 12
        run: sudo xcode-select -switch /Applications/Xcode_12.0.app
      - name: Build and test
        run: |
          xcodebuild clean test -project Radio.xcodeproj -scheme radio -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
          destination: ${{ matrix.destination }} 
